global using HemoSys.SharedKernel;
global using DevSource.Stack.Results;
global using DevSource.Stack.Notifications;
global using System.Text.Json.Serialization;
global using DevSource.Stack.Results.StatusCodeTypes;
global using DevSource.Stack.Notifications.Validations;
global using HemoSys.SchedulingService.Application.Appointments.Commands;
global using HemoSys.SchedulingService.Application.Appointments.Commands.Models;
global using HemoSys.SchedulingService.Application.Appointments.Interfaces.Services;