name: Build and Test - MS Scheduling

on:
  push:
    branches:
      - dev  
    paths:
      - 'contexts/donation-management/ms-scheduling/**'
        
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  versioning:
    runs-on: ubuntu-22.04
    name: Versioning
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./contexts/donation-management/ms-scheduling

    outputs: 
      version: ${{ steps.version.outputs.version }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - uses: codacy/git-version@2.8.0
        id: version
        with:
          release-branch: dev
          prefix: v
          
      - name: Tag Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/dev'
      
      - name: Create file version
        run: |
          echo ${{ steps.version.outputs.version }} > version.txt
          echo "{name}={version}" >> $GITHUB_OUTPUT
        if: github.ref == 'refs/heads/dev'
        
      - uses: actions/upload-artifact@v4
        with:
          name: ms-scheduling-version
          path: ms-scheduling/version.txt
        if: github.ref == 'refs/heads/dev'
        
  build-and-tests:
    needs: versioning
    runs-on: ubuntu-22.04
    name: Build and Tests
    defaults:
      run:
        working-directory: ./contexts/donation-management/ms-scheduling
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'
          
      - name: Restore
        run: dotnet restore App/App.csproj
        
      - name: Build
        run: dotnet build --no-restore --configuration Release App/App.csproj
        
      - name: Test
        run: |
          dotnet --no-restore --no-build test tests/HemoSys.SchedulingService.Tests/HemoSys.SchedulingService.Tests.csproj --configuration Release  --logger trx --results-directory "tests-results"
        if: github.ref != 'refs/heads/dev'
        
      - uses: actions/upload-artifact@v4
        with:
          name: ms-scheduling-tests-results
          path: ms-scheduling/tests/tests-results
        if: github.ref != 'refs/heads/dev'
        
  lint-check:
    needs: versioning
    runs-on: ubuntu-22.04
    name: Lint Check
    defaults:
      run:
        working-directory: ./contexts/donation-management/ms-scheduling
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          
      - uses: github/super-linter@v4
        with:
          DEFAULT_BRANCH: dev
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_YAML: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    if: github.ref != 'refs/heads/dev'
      
  code-security-check:
    needs: versioning
    runs-on: ubuntu-22.04
    name: Code Security Check
    permissions:
      security-events: write
      packages: read
      actions: read
      contents: read
    defaults:
      run:
        working-directory: ./contexts/donation-management/ms-scheduling
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          fetch-depth: 0
          
      - uses: github/codeql-action/init@v3
        name: Initialize CodeQL
        with:
          languages: csharp
          build: ${{ matrix.build }}
          
      - uses: github/codeql-action/analyze@v3
        name: Analyze with CodeQL
        with:
          languages: csharp
          query: security-and-quality.qls
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fail_on_error: ${{ matrix.fail_on_error }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        