name: Build and Test

on:
  push:
    branches:
      - dev  
    paths:
      - 'contexts/donation-management/ms-scheduling/**'
        
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  versioning:
    runs-on: ubuntu-latest
    name: Versioning
    permissions:
      contents: write
    defaults:
      run:
        working-directory: ./contexts/donation-management/ms-scheduling

    outputs: 
      version: ${{ steps.version.outputs.version }}
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with: 
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - uses: codacy/git-version@2.8.0
        id: version
        with:
          release-branch: main
          prefix: v
          
      - name: Tag Repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "::notice:: ${{ steps.version.outputs.version }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git config --global user.name "${{ github.actor }}"
          git tag -a ${{ steps.version.outputs.version }} -m "Release ${{ steps.version.outputs.version }}"
          git push --tags
        if: github.ref == 'refs/heads/main'
      
      - name: Create file version
        run: |
          echo ${{ steps.version.outputs.version }} > version.txt
          echo "::set-output name=version::${{ steps.version.outputs.version }}"
        if: github.ref == 'refs/heads/main'
        
      - uses: actions/upload-artifact@v4
        with:
          name: version
          path: version.txt
        if: github.ref == 'refs/heads/main'
        
  build-and-tests:
    needs: versioning
    runs-on: ubuntu-latest
    name: Build and Tests
    defaults:
      run:
        working-directory: ./contexts/donation-management/ms-scheduling
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
          cache: true
          cache-dependency-path: '**/packages.lock.json'
          
      - name: Restore
        run: dotnet restore ./contexts/donation-management/ms-scheduling/App/App.csproj
        
      - name: Build
        run: dotnet build --no-restore --configuration Release ./contexts/donation-management/ms-scheduling/App/App.csproj
        
      - name: Test
        run: |
          dotnet test --no-build --no-restore --configuration Release --logger trx --results-directory "tests-results"
        if: github.ref != 'refs/heads/main'
        
      - uses: actions/upload-artifact@v4
        with:
          name: dotnet-tests-results
          path: tests-results
        if: github.ref != 'refs/heads/main'
        
      - name: Publish
        run: dotnet publish --no-build --no-restore --configuration Release --output ./publish
        if: github.ref == 'refs/heads/main'
        
      - name: Tag Publish Vesion
        uses: restackio/update-json-file-action@2.1
        with:
          file-path: './publish/appsettings.json'
          key: 'Version'
          value: ${{ needs.versioning.outputs.version }}
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: API
          path: ./publish
    
  build-docker-image:
    name: Packing and Publish
    needs: [ versioning, build-and-tests ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contexts/donation-management/ms-scheduling
    
    env:
      version: ${{ needs.versioning.outputs.version }}
    
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          path: app
          merge-multiple: false

      - name: Build Docker Image
        run: |
          docker build -t ${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.version }} .

      - name: Tag Docker Image as Latest
        run: |
          docker tag ${{ vars.DOCKERHUB_REPOSITORY }}:${{ env.version }} ${{ vars.DOCKERHUB_REPOSITORY }}:latest
        if: github.ref == 'refs/heads/main'

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker Push
        run: |
          docker push --all-tags uitanmaciel/hemosys-ms-scheduling